### ISSUE TITLE
code de LaFabrique absent

### ISSUE THREAD

**Issue by mcloarec** [CapCaval/ccProjects#10]
Bonjour,

J'ai essayé d'utiliser la dernière version récupérée depuis git mais ça ne compile pas car le code de LaFabrique est absent. Même en récupérant la lib depuis le site capcaval.org ça ne marche pas car elle est obsolète je pense.

**Comment by MikArber** [comment]
Bonjour,

Merci beaucoup pour l'information. Je vais essayer de trouver un peu de  
temps pour mettre cela à jour. Autrement, si les sources vous intéressent  
elles sont aussi disponibles dans le fichier lafabrique.jar avec les  
binaires : http://lafabrique.capcaval.org/download.html

Désolé pour la gêne occasionnée.
Cordialement,

Mik

**Comment by mcloarec** [comment]
Bonjour Mickaël,
Merci pour ta réponse.
