### ISSUE TITLE
Différence entre un Componentitem et un SubComponent

### ISSUE THREAD

**Issue by mcloarec** [CapCaval/ccProjects#11]
Bonjour Mickaël,

Quelle est la différence entre ces deux notions ?

**Comment by MikArber** [comment]
Bonjour Mathieu,

La différence est assez simple :
- ComponentItem : Permet implémenter un composant en plusieurs classes. Par exemple si un composant implémente de nombreux services et éventements, il est possible de réaliser l'implémentation via plusieurs classes évitant ainsi d'avoir une seule classe avec de trop nombreuses lignes de code.
- Subcomponent : Permet d'associer des composants comme enfants d'un père. Les enfants sont automatiquement créer à la création du père et aussi accessibles à celui-çi. Cela permet de masquer une complexité, par exemple un composant père propose des événements pour recevoir des objets. Ce composant peut utiliser deux composants enfants, un premier composant gère une connexion UDP et un deuxième désérialise des champs d'octets dans des objets. Le tout géré par le père, ainsi un autre composant peut s'abonner uniquement au père sans avoir à connaitre et utiliser les enfants. De plus cela rend plus flexible de par exemple remplacer le composant UDP par un en TCP/IP.

Si tu as d'autres questions n'hésites surtout pas à me contacter : )

**Comment by mcloarec** [comment]
Merci Mickael pour ces réponses
